# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdn_northbound.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'sdn_northbound.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sdn_northbound.proto\">\n\nVlanConfig\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07vlan_id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\"2\n\x0e\x43onfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0b\x44\x65viceQuery\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\r\"=\n\nMetricData\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0f\n\x07traffic\x18\x02 \x01(\x04\x12\x11\n\ttimestamp\x18\x03 \x01(\t\";\n\x11\x46\x61ultNotification\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"/\n\x08\x46\x61ultAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\x9d\x01\n\rSDNNorthbound\x12,\n\nUpdateVlan\x12\x0b.VlanConfig\x1a\x0f.ConfigResponse\"\x00\x12.\n\rStreamMetrics\x12\x0c.DeviceQuery\x1a\x0b.MetricData\"\x00\x30\x01\x12.\n\x0bReportFault\x12\x12.FaultNotification\x1a\t.FaultAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdn_northbound_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VLANCONFIG']._serialized_start=24
  _globals['_VLANCONFIG']._serialized_end=86
  _globals['_CONFIGRESPONSE']._serialized_start=88
  _globals['_CONFIGRESPONSE']._serialized_end=138
  _globals['_DEVICEQUERY']._serialized_start=140
  _globals['_DEVICEQUERY']._serialized_end=190
  _globals['_METRICDATA']._serialized_start=192
  _globals['_METRICDATA']._serialized_end=253
  _globals['_FAULTNOTIFICATION']._serialized_start=255
  _globals['_FAULTNOTIFICATION']._serialized_end=314
  _globals['_FAULTACK']._serialized_start=316
  _globals['_FAULTACK']._serialized_end=363
  _globals['_SDNNORTHBOUND']._serialized_start=366
  _globals['_SDNNORTHBOUND']._serialized_end=523
# @@protoc_insertion_point(module_scope)
