# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sdn_northbound_pb2 as sdn__northbound__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sdn_northbound_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDNNorthboundStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateVlan = channel.unary_unary(
                '/SDNNorthbound/UpdateVlan',
                request_serializer=sdn__northbound__pb2.VlanConfig.SerializeToString,
                response_deserializer=sdn__northbound__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.StreamMetrics = channel.unary_stream(
                '/SDNNorthbound/StreamMetrics',
                request_serializer=sdn__northbound__pb2.DeviceQuery.SerializeToString,
                response_deserializer=sdn__northbound__pb2.MetricData.FromString,
                _registered_method=True)
        self.ReportFault = channel.unary_unary(
                '/SDNNorthbound/ReportFault',
                request_serializer=sdn__northbound__pb2.FaultNotification.SerializeToString,
                response_deserializer=sdn__northbound__pb2.FaultAck.FromString,
                _registered_method=True)


class SDNNorthboundServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateVlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDNNorthboundServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateVlan': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVlan,
                    request_deserializer=sdn__northbound__pb2.VlanConfig.FromString,
                    response_serializer=sdn__northbound__pb2.ConfigResponse.SerializeToString,
            ),
            'StreamMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=sdn__northbound__pb2.DeviceQuery.FromString,
                    response_serializer=sdn__northbound__pb2.MetricData.SerializeToString,
            ),
            'ReportFault': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFault,
                    request_deserializer=sdn__northbound__pb2.FaultNotification.FromString,
                    response_serializer=sdn__northbound__pb2.FaultAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SDNNorthbound', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SDNNorthbound', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDNNorthbound(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateVlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SDNNorthbound/UpdateVlan',
            sdn__northbound__pb2.VlanConfig.SerializeToString,
            sdn__northbound__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SDNNorthbound/StreamMetrics',
            sdn__northbound__pb2.DeviceQuery.SerializeToString,
            sdn__northbound__pb2.MetricData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SDNNorthbound/ReportFault',
            sdn__northbound__pb2.FaultNotification.SerializeToString,
            sdn__northbound__pb2.FaultAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
